name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.actor == github.repository_owner
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Install Nix
        uses: cachix/install-nix-action@v31.10.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install Dependencies
        run: nix develop --command npm install
      - name: Lint
        run: nix develop --command npm run lint

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.actor == github.repository_owner
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Install Nix
        uses: cachix/install-nix-action@v31.10.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: nix build
      - uses: actions/upload-artifact@v7
        with:
          name: functional-reader
          path: result
