name: Publish

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  main:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com/rxtp
          scope: '@rxtp'
      - run: npm ci
      - run: npx nx run-many --target=publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
